let date = new Date();

// Printing the date...
console.log(date);

// Printing only the date...
console.log(date.getDate())

// Printing only the month...
console.log(date.getMonth()) // Month starts from 0, hence it will be (real month - 1);

// Prining only the year...
console.log(date.getFullYear())

// Printing the day...
console.log(date.getDay()); // Sunday will be 0 and it will be incremented...

// Printing the date in custom format...
let today = date.getDate() + "/" + (date.getMonth() + 1) + "/" + date.getFullYear();
console.log(today);

// Getting hours, minutes & seconds...
console.log(date.getHours() + ":" + date.getMinutes() + ":" + date.getSeconds())